apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-exporter-security-config
  namespace: metric
data:
  config.yml: |-
    region: ap-northeast-2
    period_seconds: 300
    delay_seconds: 300
    metrics:
      - aws_namespace: AWS/GuardDuty
        aws_metric_name: FindingCount
        aws_dimensions: [Severity]
        aws_statistics: [Sum]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudwatch-exporter-security
  namespace: metric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudwatch-exporter-security
  template:
    metadata:
      labels:
        app: cloudwatch-exporter-security
    spec:
      serviceAccountName: cloudwatch-exporter
      containers:
        - name: cloudwatch-exporter
          image: prom/cloudwatch-exporter:latest
          ports:
            - containerPort: 9106
              name: metrics
          env:
            - name: AWS_REGION
              value: "ap-northeast-2"
          args:
            - "/etc/cloudwatch-exporter/config.yml"
          volumeMounts:
            - name: config
              mountPath: /etc/cloudwatch-exporter
      volumes:
        - name: config
          configMap:
            name: cloudwatch-exporter-security-config

---
apiVersion: v1
kind: Service
metadata:
  name: cloudwatch-exporter-security
  namespace: metric
  labels:
    app: cloudwatch-exporter-security
spec:
  ports:
    - port: 9106
      targetPort: 9106
      name: metrics
  selector:
    app: cloudwatch-exporter-security
