apiVersion: v1
kind: ConfigMap
metadata:
  name: guardduty-prometheus-rules
  namespace: metric
  labels:
    prometheus: kube-prometheus
    role: alert-rules
data:
  guardduty-rules.yml: |-
    groups:
      - name: SecurityAlerts
        rules:
          # GuardDuty High Severity Findings
          - alert: GuardDutyHighSeverityFinding
            expr: aws_guardduty_finding_count{severity="High"} > 0
            for: 0m
            labels:
              severity: critical
            annotations:
              summary: "GuardDuty High Severity Finding Detected"
              description: "High severity security finding detected in GuardDuty. Immediate investigation required."

          # DDoS Attack Detection
          - alert: DDoSAttackDetected
            expr: aws_ddos_protection_ddos_detected > 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "DDoS Attack Detected"
              description: "DDoS attack has been detected and AWS Shield is actively mitigating."

          # Unusual Network Traffic
          - alert: UnusualNetworkTraffic
            expr: rate(aws_ec2_network_in_bytes[5m]) > 10000000  # 10MB/s threshold
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Unusual Network Traffic Detected"
              description: "Network traffic spike detected. Current rate: {{ $value }} bytes/sec"

          # GuardDuty Multiple Findings
          - alert: GuardDutyMultipleFindings
            expr: increase(aws_guardduty_finding_count[1h]) >= 5
            for: 0m
            labels:
              severity: warning
            annotations:
              summary: "Multiple GuardDuty Findings"
              description: "{{ $value }} GuardDuty findings detected in the last hour."

          # CloudTrail Log Ingestion Stopped
          - alert: CloudTrailLogsStopped
            expr: aws_cloudwatchlogs_incoming_log_events{log_group_name="/aws/cloudtrail"} == 0
            for: 15m
            labels:
              severity: critical
            annotations:
              summary: "CloudTrail Logs Stopped"
              description: "No CloudTrail logs have been received for 15 minutes. Audit trail may be compromised."

          # Suspicious API Activity
          - alert: SuspiciousAPIActivity
            expr: rate(aws_cloudwatchlogs_incoming_log_events{log_group_name="/aws/cloudtrail"}[5m]) > 100
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "High Volume API Activity"
              description: "Unusually high API activity detected: {{ $value }} events/sec"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: security-serviceMonitor
  namespace: metric
data:
  cloudwatch-security.yaml: |-
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: cloudwatch-security
      namespace: metric
    spec:
      selector:
        matchLabels:
          app: cloudwatch-exporter-security
      endpoints:
        - port: metrics
          interval: 60s
          path: /metrics

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudwatch-exporter-security
  namespace: metric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudwatch-exporter-security
  template:
    metadata:
      labels:
        app: cloudwatch-exporter-security
    spec:
      serviceAccountName: cloudwatch-exporter
      containers:
        - name: cloudwatch-exporter
          image: prom/cloudwatch-exporter:latest
          ports:
            - containerPort: 9106
              name: metrics
          env:
            - name: AWS_REGION
              value: "ap-northeast-2"
          args:
            - "--config.file=/etc/cloudwatch-exporter/config.yml"
          volumeMounts:
            - name: config
              mountPath: /etc/cloudwatch-exporter
      volumes:
        - name: config
          configMap:
            name: cloudwatch-exporter-security-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-exporter-security-config
  namespace: metric
data:
  config.yml: |-
    region: ap-northeast-2
    period_seconds: 300
    delay_seconds: 300
    metrics:
      - aws_namespace: AWS/GuardDuty
        aws_metric_name: FindingCount
        aws_dimensions: [Severity]
        aws_statistics: [Sum]
      
      - aws_namespace: AWS/DDoSProtection  
        aws_metric_name: DDoSDetected
        aws_statistics: [Maximum]
      
      - aws_namespace: AWS/CloudWatchLogs
        aws_metric_name: IncomingLogEvents
        aws_dimensions: [LogGroupName]
        aws_statistics: [Sum]
      
      - aws_namespace: AWS/EC2
        aws_metric_name: NetworkIn
        aws_statistics: [Average]
        
      - aws_namespace: AWS/EC2
        aws_metric_name: NetworkOut  
        aws_statistics: [Average]

---
apiVersion: v1
kind: Service
metadata:
  name: cloudwatch-exporter-security
  namespace: metric
  labels:
    app: cloudwatch-exporter-security
spec:
  ports:
    - port: 9106
      targetPort: 9106
      name: metrics
  selector:
    app: cloudwatch-exporter-security