# environments/prod/app.yaml
# Production Environment Configuration
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    environment: prod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-prod
  namespace: prod
  labels:
    app: test-app
    environment: prod
spec:
  replicas: 3  # Higher replicas for production
  selector:
    matchLabels:
      app: test-app
      environment: prod
  template:
    metadata:
      labels:
        app: test-app
        environment: prod
    spec:
      containers:
      - name: test-app
        image: 177716289679.dkr.ecr.ap-northeast-2.amazonaws.com/izza/test:v1.0.1  # Stable version
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "64Mi"    # Higher resources for prod
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:       # Health checks for prod
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: test-app-service-prod
  namespace: prod
  labels:
    app: test-app
    environment: prod
spec:
  selector:
    app: test-app
    environment: prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP