# environments/app/backend-dev.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-dev-service-account
  namespace: app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::177716289679:role/EKSDevBackendAppRole

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dev
  namespace: app
  labels:
    app: backend
    environment: dev
    component: api
spec:
  replicas: 3
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
  selector:
    matchLabels:
      app: backend
      environment: dev
  template:
    metadata:
      labels:
        app: backend
        environment: dev
        component: api
    spec:
      serviceAccountName: backend-dev-service-account
      nodeSelector:
        workload: app
      containers:
      - name: backend
        image: 177716289679.dkr.ecr.ap-northeast-2.amazonaws.com/izza/backend:development-20250902-061805-6147a01
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: ENVIRONMENT
          value: "development"
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: AWS_DEFAULT_REGION
          value: "ap-northeast-2"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: backend-dev-service
  namespace: app
  labels:
    app: backend
    environment: dev
spec:
  selector:
    app: backend
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  type: ClusterIP