# environments/app/backend-prod.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-prod-service-account
  namespace: app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::177716289679:role/EKSDevBackendAppRole

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prod
  namespace: app
  labels:
    app: backend
    environment: prod
    component: api
spec:
  replicas: 2  # More replicas for production
  selector:
    matchLabels:
      app: backend
      environment: prod
  template:
    metadata:
      labels:
        app: backend
        environment: prod
        component: api
    spec:
      serviceAccountName: backend-prod-service-account
      nodeSelector:
        workload: app
      containers:
      - name: backend
        image: 177716289679.dkr.ecr.ap-northeast-2.amazonaws.com/izza/backend:development-20250827-074532-6085c5f
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: ENVIRONMENT
          value: "production"
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: AWS_DEFAULT_REGION
          value: "ap-northeast-2"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: backend-prod-service
  namespace: app
  labels:
    app: backend
    environment: prod
spec:
  selector:
    app: backend
    environment: prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  type: ClusterIP