apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: izza-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aws-izza/izza-cd.git
    targetRevision: main
    path: environments/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: metric
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true