# environments/dev/app.yaml
# Development Environment Configuration
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    environment: dev

---
# Ensure the service account exists with IRSA annotation
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service-account
  namespace: dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::177716289679:role/EKSDevBackendAppRole

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dev
  namespace: dev
  labels:
    app: backend
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      environment: dev
  template:
    metadata:
      labels:
        app: backend
        environment: dev
    spec:
      serviceAccountName: backend-service-account
      containers:
      - name: backend
        image: 177716289679.dkr.ecr.ap-northeast-2.amazonaws.com/izza/backend:development-20250825-025728-d1250db
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: ENVIRONMENT
          value: "development"
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: AWS_DEFAULT_REGION
          value: "ap-northeast-2"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        # Spring Boot health checks - adjusted for secret loading time
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120  # More time for secret loading
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60   # More time for startup
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-dev
  namespace: dev
  labels:
    app: backend
    environment: dev
spec:
  selector:
    app: backend
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  type: ClusterIP