# environments/dev/app.yaml
# Development Environment Configuration
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    environment: dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dev
  namespace: dev
  labels:
    app: backend
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      environment: dev
  template:
    metadata:
      labels:
        app: backend
        environment: dev
    spec:
      serviceAccountName: backend-service-account
      containers:
      - name: backend
        image: 177716289679.dkr.ecr.ap-northeast-2.amazonaws.com/izza/backend:development-20250819-094355-3ad1f53
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: ENVIRONMENT
          value: "development"
        - name: AWS_REGION
          value: "ap-northeast-2"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        # Spring Boot health checks
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: test-app-service-dev
  namespace: dev
  labels:
    app: backend
    environment: dev
spec:
  selector:
    app: backend
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  type: ClusterIP